server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: API-GATEWAY-SERVICE

  cloud:
    gateway:
      routes:
        - id: Login
          uri: http://localhost:9081
          predicates:
            - Path=/auth/**
          filters:
            - name: AuthenticationFilter
        - id: product
          uri: http://localhost:8099
          predicates:
            - Path=/product/**
          filters:
            - name: AuthenticationFilter
        - id: cart
          uri: http://localhost:8084
          predicates:
            - Path=/api/cart/**
          filters:
            - name: AuthenticationFilter
